version: '3.1'
services:

  postgres:
    restart: always
    image: postgres:latest

  clair:
    restart: always
    depends_on:
      - postgres
    image: quay.io/coreos/clair:v2.0.0
    ports:
      - 6060:6060
      - 6061:6061
    volumes:
      - /tmp:/tmp
      - ./clair_config:/etc/clair
#    command: [-config, /config/config.yaml]

#    image: postgres:latest
#    image: quay.io/coreos/clair-git:latest
